version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ms-menu
      MONGO_INITDB_ROOT_PASSWORD: MgDock3r
    ports:
      - "27017:27017"
    networks:
      - ms-menu

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ms-menu
      ME_CONFIG_BASICAUTH_PASSWORD: MgDock3r
      ME_CONFIG_MONGODB_ADMINUSERNAME: ms-menu
      ME_CONFIG_MONGODB_ADMINPASSWORD: MgDock3r
      ME_CONFIG_MONGODB_URL: mongodb://ms-menu:MgDock3r@mongo:27017/ms-menu?authSource=admin
    links:
      - mongo
    networks:
      - ms-menu

networks: 
    ms-menu:
      driver: bridge