version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "PgD0ck3r"
    ports:
      - 5432:5432
    networks:
      - ms-menu
  cache:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    networks:
      - ms-menu

networks: 
    ms-menu:
      driver: bridge