version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "PgD0ck3r"
    ports:
      - 5432:5432
    networks:
      - ms-menu

networks: 
    ms-menu:
      driver: bridge